<!doctype html>
 <html>
 <head>
 	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
 	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
 	<title>Whitesquare</title>
 	<link rel="stylesheet" href="css/styles.css" type="text/css">
 	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css">
 </head>
 <body>
 	<div id="wrapper">
 		<header>
 			<a href="/"><img src="images/logo.png" alt="Whitesquare logo"></a>
 			<form name="search" action="#" method="get">
 				<input type="text" name="q" placeholder="Search"><button type="submit">GO</button>
 			</form>
 		</header>
 		<nav>
 			<ul class="top-menu">
 				<li><a href="/home/">HOME</a></li>
 				<li class="active">ABOUT US</li>
 				<li><a href="/partners/">PARTNERS</a></li>
 				<li><a href="/projects/">PROJECTS</a></li>
 				<li><a href="/contacts/">CONTACTS</a></li>
 			</ul>
 		</nav>

 		<div id="heading">
 			<h1>ABOUT US</h1>
 		</div>
        <div id="menu">
        <ul>
          <h3><li>LOREM IPSUME</li></h3>
          <h3><li>DONEC</li></h3>
          <h3><li>VESTIBULUM</li></h3>
          <h3><li>ETIAM</li></h3>
          <h3><li>PHASELLUS</li></h3>
          <h3><li>CRAS</li></h3>
        </ul>
        </div>
 		<aside></aside>
 		<section></section>
 		<p><h3>What is Lorem Ipsum?
 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</h3></p>

         <p><h3>Why do we use it?
 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</h3></p>

          <p><h3>Britain is one of the most highly industrialised countries in the
world: for every person employed in agriculture 12 are employed in industry. The original base of British industry was coal-mining, iron and steel and textiles. Today the most productive sectors include high-tech industries, chemicals, finance and the service sectors, especially banking, insurance and tourism.</h3></p>

          <p><h3>Birmingham developed engineering, chemicals, electronics and car
manufacture. Cambridge is famous for software engineering (making programs for computers) and bio-chemical and bio-genetic products. Cattle-farming is the speciality of the west of England, Northern Ireland and Scotland. Wheat and fruit are widely grown in the south-east of England. Near the east and north-east coast of England and Scotland there are vast reserves of oil and gas. The UK is a member of OPEC — the Oil Producers and Exporters Cartel</h3></p>

 	</div>

    <div id="footer">
        <h3>Our Contacts</h3>
        <p align="right"><a href="/"><img src="images/footer-logo.png"></a></p>
        <a href="/"><img src="images/social.png"></a>
    </div>

 </body>
 </html> 
